server:
  port: 7002
spring:
    application:
      name: cloud-eureka-server-7001
eureka:
  instance:
    hostname: jonn-7002
  client:
    #false 表示不想向注册中心注册自己
    register-with-eureka: true
    #false 表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://jonn-7001:7001/eureka/
debug: true
