server:
  port: 9003
spring:
  application:
    name: nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
service:
  payment:
    provider: http://nacos-payment-provider